import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  client: {
    NEXT_PUBLIC_CHAIN: z.string().min(1),
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().min(1),
    NEXT_PUBLIC_GRAPHQL_URL: z.string().min(1),
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_HOLESKY: z.string().min(1),
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_ANVIL: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_HOLESKY: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_ANVIL: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_HOLESKY: z.string().min(1),
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_ANVIL: z.string().min(1),
  },
  runtimeEnv: {
    NEXT_PUBLIC_CHAIN: process.env.NEXT_PUBLIC_CHAIN,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL:
      process.env.NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL,
    NEXT_PUBLIC_GRAPHQL_URL: process.env.NEXT_PUBLIC_GRAPHQL_URL,
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS:
      process.env.NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS,
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS:
      process.env.NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS,
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS:
      process.env.NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS,
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_HOLESKY:
      process.env.NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_HOLESKY,
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_HOLESKY:
      process.env.NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_HOLESKY,
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_HOLESKY:
      process.env.NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_HOLESKY,
    NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_ANVIL:
      process.env.NEXT_PUBLIC_VANILLA_REGISTRY_ADDRESS_ANVIL,
    NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_ANVIL:
      process.env.NEXT_PUBLIC_MEV_COMMIT_AVS_V3_ADDRESS_ANVIL,
    NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_ANVIL:
      process.env.NEXT_PUBLIC_MEV_COMMIT_MIDDLEWARE_ADDRESS_ANVIL,
  },
})
